package pers.zhentao.cityinfo.pojo;

import java.util.Date;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.id
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_type
     *
     * @mbggenerated
     */
    private Short infoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_title
     *
     * @mbggenerated
     */
    private String infoTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_content
     *
     * @mbggenerated
     */
    private String infoContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_linkman
     *
     * @mbggenerated
     */
    private String infoLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_phone
     *
     * @mbggenerated
     */
    private String infoPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_email
     *
     * @mbggenerated
     */
    private String infoEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_date
     *
     * @mbggenerated
     */
    private Date infoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_state
     *
     * @mbggenerated
     */
    private String infoState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_payfor
     *
     * @mbggenerated
     */
    private String infoPayfor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.id
     *
     * @return the value of tb_info.id
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.id
     *
     * @param id the value for tb_info.id
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_type
     *
     * @return the value of tb_info.info_type
     *
     * @mbggenerated
     */
    public Short getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_type
     *
     * @param infoType the value for tb_info.info_type
     *
     * @mbggenerated
     */
    public void setInfoType(Short infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_title
     *
     * @return the value of tb_info.info_title
     *
     * @mbggenerated
     */
    public String getInfoTitle() {
        return infoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_title
     *
     * @param infoTitle the value for tb_info.info_title
     *
     * @mbggenerated
     */
    public void setInfoTitle(String infoTitle) {
        this.infoTitle = infoTitle == null ? null : infoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_content
     *
     * @return the value of tb_info.info_content
     *
     * @mbggenerated
     */
    public String getInfoContent() {
        return infoContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_content
     *
     * @param infoContent the value for tb_info.info_content
     *
     * @mbggenerated
     */
    public void setInfoContent(String infoContent) {
        this.infoContent = infoContent == null ? null : infoContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_linkman
     *
     * @return the value of tb_info.info_linkman
     *
     * @mbggenerated
     */
    public String getInfoLinkman() {
        return infoLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_linkman
     *
     * @param infoLinkman the value for tb_info.info_linkman
     *
     * @mbggenerated
     */
    public void setInfoLinkman(String infoLinkman) {
        this.infoLinkman = infoLinkman == null ? null : infoLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_phone
     *
     * @return the value of tb_info.info_phone
     *
     * @mbggenerated
     */
    public String getInfoPhone() {
        return infoPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_phone
     *
     * @param infoPhone the value for tb_info.info_phone
     *
     * @mbggenerated
     */
    public void setInfoPhone(String infoPhone) {
        this.infoPhone = infoPhone == null ? null : infoPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_email
     *
     * @return the value of tb_info.info_email
     *
     * @mbggenerated
     */
    public String getInfoEmail() {
        return infoEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_email
     *
     * @param infoEmail the value for tb_info.info_email
     *
     * @mbggenerated
     */
    public void setInfoEmail(String infoEmail) {
        this.infoEmail = infoEmail == null ? null : infoEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_date
     *
     * @return the value of tb_info.info_date
     *
     * @mbggenerated
     */
    public Date getInfoDate() {
        return infoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_date
     *
     * @param infoDate the value for tb_info.info_date
     *
     * @mbggenerated
     */
    public void setInfoDate(Date infoDate) {
        this.infoDate = infoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_state
     *
     * @return the value of tb_info.info_state
     *
     * @mbggenerated
     */
    public String getInfoState() {
        return infoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_state
     *
     * @param infoState the value for tb_info.info_state
     *
     * @mbggenerated
     */
    public void setInfoState(String infoState) {
        this.infoState = infoState == null ? null : infoState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_payfor
     *
     * @return the value of tb_info.info_payfor
     *
     * @mbggenerated
     */
    public String getInfoPayfor() {
        return infoPayfor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_payfor
     *
     * @param infoPayfor the value for tb_info.info_payfor
     *
     * @mbggenerated
     */
    public void setInfoPayfor(String infoPayfor) {
        this.infoPayfor = infoPayfor == null ? null : infoPayfor.trim();
    }
}