package pers.zhentao.cityinfo.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public InfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIsNull() {
            addCriterion("info_type is null");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIsNotNull() {
            addCriterion("info_type is not null");
            return (Criteria) this;
        }

        public Criteria andInfoTypeEqualTo(Short value) {
            addCriterion("info_type =", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotEqualTo(Short value) {
            addCriterion("info_type <>", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeGreaterThan(Short value) {
            addCriterion("info_type >", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("info_type >=", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLessThan(Short value) {
            addCriterion("info_type <", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLessThanOrEqualTo(Short value) {
            addCriterion("info_type <=", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIn(List<Short> values) {
            addCriterion("info_type in", values, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotIn(List<Short> values) {
            addCriterion("info_type not in", values, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeBetween(Short value1, Short value2) {
            addCriterion("info_type between", value1, value2, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotBetween(Short value1, Short value2) {
            addCriterion("info_type not between", value1, value2, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTitleIsNull() {
            addCriterion("info_title is null");
            return (Criteria) this;
        }

        public Criteria andInfoTitleIsNotNull() {
            addCriterion("info_title is not null");
            return (Criteria) this;
        }

        public Criteria andInfoTitleEqualTo(String value) {
            addCriterion("info_title =", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleNotEqualTo(String value) {
            addCriterion("info_title <>", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleGreaterThan(String value) {
            addCriterion("info_title >", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleGreaterThanOrEqualTo(String value) {
            addCriterion("info_title >=", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleLessThan(String value) {
            addCriterion("info_title <", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleLessThanOrEqualTo(String value) {
            addCriterion("info_title <=", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleLike(String value) {
            addCriterion("info_title like", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleNotLike(String value) {
            addCriterion("info_title not like", value, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleIn(List<String> values) {
            addCriterion("info_title in", values, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleNotIn(List<String> values) {
            addCriterion("info_title not in", values, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleBetween(String value1, String value2) {
            addCriterion("info_title between", value1, value2, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoTitleNotBetween(String value1, String value2) {
            addCriterion("info_title not between", value1, value2, "infoTitle");
            return (Criteria) this;
        }

        public Criteria andInfoContentIsNull() {
            addCriterion("info_content is null");
            return (Criteria) this;
        }

        public Criteria andInfoContentIsNotNull() {
            addCriterion("info_content is not null");
            return (Criteria) this;
        }

        public Criteria andInfoContentEqualTo(String value) {
            addCriterion("info_content =", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentNotEqualTo(String value) {
            addCriterion("info_content <>", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentGreaterThan(String value) {
            addCriterion("info_content >", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentGreaterThanOrEqualTo(String value) {
            addCriterion("info_content >=", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentLessThan(String value) {
            addCriterion("info_content <", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentLessThanOrEqualTo(String value) {
            addCriterion("info_content <=", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentLike(String value) {
            addCriterion("info_content like", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentNotLike(String value) {
            addCriterion("info_content not like", value, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentIn(List<String> values) {
            addCriterion("info_content in", values, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentNotIn(List<String> values) {
            addCriterion("info_content not in", values, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentBetween(String value1, String value2) {
            addCriterion("info_content between", value1, value2, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoContentNotBetween(String value1, String value2) {
            addCriterion("info_content not between", value1, value2, "infoContent");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanIsNull() {
            addCriterion("info_linkman is null");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanIsNotNull() {
            addCriterion("info_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanEqualTo(String value) {
            addCriterion("info_linkman =", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanNotEqualTo(String value) {
            addCriterion("info_linkman <>", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanGreaterThan(String value) {
            addCriterion("info_linkman >", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("info_linkman >=", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanLessThan(String value) {
            addCriterion("info_linkman <", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanLessThanOrEqualTo(String value) {
            addCriterion("info_linkman <=", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanLike(String value) {
            addCriterion("info_linkman like", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanNotLike(String value) {
            addCriterion("info_linkman not like", value, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanIn(List<String> values) {
            addCriterion("info_linkman in", values, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanNotIn(List<String> values) {
            addCriterion("info_linkman not in", values, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanBetween(String value1, String value2) {
            addCriterion("info_linkman between", value1, value2, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoLinkmanNotBetween(String value1, String value2) {
            addCriterion("info_linkman not between", value1, value2, "infoLinkman");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneIsNull() {
            addCriterion("info_phone is null");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneIsNotNull() {
            addCriterion("info_phone is not null");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneEqualTo(String value) {
            addCriterion("info_phone =", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneNotEqualTo(String value) {
            addCriterion("info_phone <>", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneGreaterThan(String value) {
            addCriterion("info_phone >", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("info_phone >=", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneLessThan(String value) {
            addCriterion("info_phone <", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneLessThanOrEqualTo(String value) {
            addCriterion("info_phone <=", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneLike(String value) {
            addCriterion("info_phone like", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneNotLike(String value) {
            addCriterion("info_phone not like", value, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneIn(List<String> values) {
            addCriterion("info_phone in", values, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneNotIn(List<String> values) {
            addCriterion("info_phone not in", values, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneBetween(String value1, String value2) {
            addCriterion("info_phone between", value1, value2, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoPhoneNotBetween(String value1, String value2) {
            addCriterion("info_phone not between", value1, value2, "infoPhone");
            return (Criteria) this;
        }

        public Criteria andInfoEmailIsNull() {
            addCriterion("info_email is null");
            return (Criteria) this;
        }

        public Criteria andInfoEmailIsNotNull() {
            addCriterion("info_email is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEmailEqualTo(String value) {
            addCriterion("info_email =", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailNotEqualTo(String value) {
            addCriterion("info_email <>", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailGreaterThan(String value) {
            addCriterion("info_email >", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailGreaterThanOrEqualTo(String value) {
            addCriterion("info_email >=", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailLessThan(String value) {
            addCriterion("info_email <", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailLessThanOrEqualTo(String value) {
            addCriterion("info_email <=", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailLike(String value) {
            addCriterion("info_email like", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailNotLike(String value) {
            addCriterion("info_email not like", value, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailIn(List<String> values) {
            addCriterion("info_email in", values, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailNotIn(List<String> values) {
            addCriterion("info_email not in", values, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailBetween(String value1, String value2) {
            addCriterion("info_email between", value1, value2, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoEmailNotBetween(String value1, String value2) {
            addCriterion("info_email not between", value1, value2, "infoEmail");
            return (Criteria) this;
        }

        public Criteria andInfoDateIsNull() {
            addCriterion("info_date is null");
            return (Criteria) this;
        }

        public Criteria andInfoDateIsNotNull() {
            addCriterion("info_date is not null");
            return (Criteria) this;
        }

        public Criteria andInfoDateEqualTo(Date value) {
            addCriterion("info_date =", value, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateNotEqualTo(Date value) {
            addCriterion("info_date <>", value, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateGreaterThan(Date value) {
            addCriterion("info_date >", value, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateGreaterThanOrEqualTo(Date value) {
            addCriterion("info_date >=", value, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateLessThan(Date value) {
            addCriterion("info_date <", value, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateLessThanOrEqualTo(Date value) {
            addCriterion("info_date <=", value, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateIn(List<Date> values) {
            addCriterion("info_date in", values, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateNotIn(List<Date> values) {
            addCriterion("info_date not in", values, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateBetween(Date value1, Date value2) {
            addCriterion("info_date between", value1, value2, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoDateNotBetween(Date value1, Date value2) {
            addCriterion("info_date not between", value1, value2, "infoDate");
            return (Criteria) this;
        }

        public Criteria andInfoStateIsNull() {
            addCriterion("info_state is null");
            return (Criteria) this;
        }

        public Criteria andInfoStateIsNotNull() {
            addCriterion("info_state is not null");
            return (Criteria) this;
        }

        public Criteria andInfoStateEqualTo(String value) {
            addCriterion("info_state =", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateNotEqualTo(String value) {
            addCriterion("info_state <>", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateGreaterThan(String value) {
            addCriterion("info_state >", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateGreaterThanOrEqualTo(String value) {
            addCriterion("info_state >=", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateLessThan(String value) {
            addCriterion("info_state <", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateLessThanOrEqualTo(String value) {
            addCriterion("info_state <=", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateLike(String value) {
            addCriterion("info_state like", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateNotLike(String value) {
            addCriterion("info_state not like", value, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateIn(List<String> values) {
            addCriterion("info_state in", values, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateNotIn(List<String> values) {
            addCriterion("info_state not in", values, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateBetween(String value1, String value2) {
            addCriterion("info_state between", value1, value2, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoStateNotBetween(String value1, String value2) {
            addCriterion("info_state not between", value1, value2, "infoState");
            return (Criteria) this;
        }

        public Criteria andInfoPayforIsNull() {
            addCriterion("info_payfor is null");
            return (Criteria) this;
        }

        public Criteria andInfoPayforIsNotNull() {
            addCriterion("info_payfor is not null");
            return (Criteria) this;
        }

        public Criteria andInfoPayforEqualTo(String value) {
            addCriterion("info_payfor =", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforNotEqualTo(String value) {
            addCriterion("info_payfor <>", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforGreaterThan(String value) {
            addCriterion("info_payfor >", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforGreaterThanOrEqualTo(String value) {
            addCriterion("info_payfor >=", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforLessThan(String value) {
            addCriterion("info_payfor <", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforLessThanOrEqualTo(String value) {
            addCriterion("info_payfor <=", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforLike(String value) {
            addCriterion("info_payfor like", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforNotLike(String value) {
            addCriterion("info_payfor not like", value, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforIn(List<String> values) {
            addCriterion("info_payfor in", values, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforNotIn(List<String> values) {
            addCriterion("info_payfor not in", values, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforBetween(String value1, String value2) {
            addCriterion("info_payfor between", value1, value2, "infoPayfor");
            return (Criteria) this;
        }

        public Criteria andInfoPayforNotBetween(String value1, String value2) {
            addCriterion("info_payfor not between", value1, value2, "infoPayfor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}